### PR TITLE
Normalize whitespace on local project files not imported from elsewhere

### PR DESCRIPTION
**Pull request by smaresca**
Normalize whitespace converting \t tabs to spaces across files that are "local" to the project and not imported from elsewhere.  I am not expressing a personal stance on style here, just trying to match what seems to be the convention (spaces not tabs, 2 spaces per tabstop).

### CODE REVIEW

**Comment by smaresca** [comment]
@dalathegreat Per conversation yesterday. Let me know if you or other maintainers have different preferences

**Comment by lenvm** [comment]
@smaresca, I suggest to add a `.clang-format` file to the root of the repository, such as the one found [here](https://github.com/kehanXue/google-style-clang-format/blob/e23cc720f89dc7548a64dd719ac4dbdf0a0ef6a4/.clang-format). The [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html) uses spaces instead of tabs, and is one of the built-in style guides. [clang-format](https://clang.llvm.org/docs/ClangFormat.html) can then be used to automatically update the coding style.

Using a pre-commit git hook would allow checking if the code confirms to the defined style guide, before committing any changes. A pre-commit git hook that checks the clang format can be installed using a `.pre-commit-config.yaml` file such as the one found [here](https://github.com/blackmagic-debug/blackmagic/blob/d0c8bb7c84a96bd743d0b104610896c53c7fd893/.pre-commit-config.yaml#L4-L9).

**Comment by lenvm** [comment]
The solution proposed is implemented in pull request https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/pull/82

**Comment by dalathegreat** [comment]
@smaresca Closing this, since the `.clang-format` nicely solves this for future!

**Pull request closed without merging**
